spring:
  profiles:
    active: development
  application:
    name: notification
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/notification
    username: ornaccode
    password: password
  # JPA propertiesa
  jpa:
    hibernate:
      ddl-auto: create-drop # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: localhost:5672

# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8082 #set your port

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

rabbitmq:
    exchanges:
        internal: internal.exchange
    queues:
        notification: notification.queue
    routing-keys:
        internal-notification: internal.notification.routing-key